version: '3.8'
services:
  frontend:
    environment:
      - REACT_APP_SCRAPER_URL=http://scraper-service:8011
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
  backend:
    environment:
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthz || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
  scraper-service:
    environment:
      - CRAWL_DELAY_MS=2000
      - MAX_CONCURRENCY=2
