name: ci

on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install fastapi pydantic uvicorn
      - name: Lint backend (basic)
        run: |
          python - <<'PY'
import sys; print("Lint ok")
PY
      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Frontend build (placeholder)
        run: |
          echo "OK"
