# docker-compose.additions.yml (overlay for domain services)
services:
  orchestrator_8001:
    build:
      context: ..
      dockerfile: app/services/orchestrator-8001/Dockerfile
    environment:
      SERVICE_NAME: orchestrator-8001
      TELEMETRY_URL: http://telemetry_gw_8030:8030
    depends_on:
      telemetry_gw_8030:
        condition: service_started
    ports: ["8101:8001"]

  address_lookup_8022:
    build:
      context: ..
      dockerfile: app/services/address-8022/Dockerfile
    environment:
      SERVICE_NAME: address-8022
      TELEMETRY_URL: http://telemetry_gw_8030:8030
      MAPILLARY_TOKEN: ${MAPILLARY_TOKEN:-}
      ORS_API_KEY: ${ORS_API_KEY:-}
    depends_on:
      telemetry_gw_8030:
        condition: service_started
    ports: ["8022:8022"]

  ai_gateway_8023:
    build:
      context: ..
      dockerfile: app/services/ai-gateway-8023/Dockerfile
    environment:
      SERVICE_NAME: ai-gateway-8023
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      TELEMETRY_URL: http://telemetry_gw_8030:8030
      AI_MAX_RPM: ${AI_MAX_RPM}
      AI_MAX_TOKENS_PER_MIN: ${AI_MAX_TOKENS_PER_MIN}
      AI_BUDGET_USD_DAILY: ${AI_BUDGET_USD_DAILY}
      AI_COST_PER_1K_TOKENS_USD: ${AI_COST_PER_1K_TOKENS_USD}
    depends_on:
      telemetry_gw_8030:
        condition: service_started
    ports: ["8023:8023"]

  vision_ai_8024:
    build:
      context: ..
      dockerfile: app/services/vision-8024/Dockerfile
    environment:
      SERVICE_NAME: vision-8024
      TELEMETRY_URL: http://telemetry_gw_8030:8030
    depends_on:
      telemetry_gw_8030:
        condition: service_started
    ports: ["8024:8024"]

  mapping_intel_8025:
    build:
      context: ..
      dockerfile: app/services/mapping-8025/Dockerfile
    environment:
      SERVICE_NAME: mapping-8025
      TELEMETRY_URL: http://telemetry_gw_8030:8030
      NOMINATIM_EMAIL: ${NOMINATIM_EMAIL}
      USGS_USER_AGENT: ${USGS_USER_AGENT}
    depends_on:
      telemetry_gw_8030:
        condition: service_started
    ports: ["8025:8025"]

  quality_engine_8026:
    build:
      context: ..
      dockerfile: app/services/quality-8026/Dockerfile
    environment:
      SERVICE_NAME: quality-8026
      TELEMETRY_URL: http://telemetry_gw_8030:8030
    depends_on:
      telemetry_gw_8030:
        condition: service_started
    ports: ["8026:8026"]

  osint_contacts_8027:
    build:
      context: ..
      dockerfile: app/services/osint-8027/Dockerfile
    environment:
      SERVICE_NAME: osint-8027
      TELEMETRY_URL: http://telemetry_gw_8030:8030
    depends_on:
      telemetry_gw_8030:
        condition: service_started
    ports: ["8027:8027"]

  event_monitor_8028:
    build:
      context: ..
      dockerfile: app/services/events-8028/Dockerfile
    environment:
      SERVICE_NAME: events-8028
      TELEMETRY_URL: http://telemetry_gw_8030:8030
    depends_on:
      telemetry_gw_8030:
        condition: service_started
    ports: ["8028:8028"]

  onboarding_8034:
    build:
      context: ..
      dockerfile: app/services/onboarding-8034/Dockerfile
    environment:
      SERVICE_NAME: onboarding-8034
      TELEMETRY_URL: http://telemetry_gw_8030:8030
      DATABASE_URL: postgresql://user:pass@postgres:5432/app
    depends_on:
      telemetry_gw_8030:
        condition: service_started
    ports: ["8034:8034"]
