# Local tiles & imagery overlay
services:
  tileserver_gl:
    image: maptiler/tileserver-gl
    volumes:
      - ./tiles:/data
    ports: ["8080:80"]
    environment:
      - MBTILES=/data/*.mbtiles
  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    ports: ["8081:8000"]
    environment:
      - CPL_VSIL_CURL_ALLOWED_EXTENSIONS=.tif,.tiff,.zip
    volumes:
      - ./imagery:/opt/data:ro
  geoserver:
    image: kartoza/geoserver:2.23.2
    ports: ["8082:8080"]
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - ./geoserver_data:/opt/geoserver_data
  postgis:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gis
    ports: ["5433:5432"]
    volumes:
      - ./pgdata:/var/lib/postgresql/data
