name: DevOps Hardening CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ "*" ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run targeted backend tests
        run: |
          python -m pytest backend/tests/test_sequences_engine.py -q

      - name: Build backend image
        run: |
          docker build -t fishmouth/backend-ci ./backend

      - name: Trivy scan (backend image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: fishmouth/backend-ci
          format: table
          exit-code: '1'
          ignore-unfixed: true

      - name: Validate SQL migrations
        run: |
          find backend/migrations -name "*.sql" -print -exec python -c "import pathlib; pathlib.Path('{}').read_text()" \;

      - name: Archive build artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: backend-build-context
          path: |
            backend/Dockerfile
            backend/requirements.txt
            backend/tests/test_sequences_engine.py
